### ISSUE TITLE
Error after Updating

### ISSUE THREAD

**Issue by gschaynes** [Willmac16/homebridge-nuvo#15]
Has anyone else had this issue with their HA configuration? 

I'm seeing this in the log after updating to the newest version of Homebridge and Homebridge-Nuvo:

[2/28/2022, 3:57:00 PM] [homebridge-nuvo] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside write handler for characteristic: Cannot read property 'zoneOn' of undefined. See https://git.io/JtMGR for more info.

**Comment by Willmac16** [comment]
You might need to reset/delete your cached accessories in order for things to work

**Comment by Willmac16** [comment]
If you are using the homebridge UI 

https://github.com/oznu/homebridge-config-ui-x/issues/525
This has photos with the steps

You can also delete the file in the homebridge folder (accessories/cached_accesories if I'm remembering correctly)

**Comment by gschaynes** [comment]
That worked great, now though it won't re-add my speakers back into Homebridge for some reason

**Comment by Willmac16** [comment]
Into homebridge or into HomeKit? Usually, the home app will drop it into a default room without prompting you if devices are added after you add the bridge.

**Comment by gschaynes** [comment]
Into Homebridge. I inherited this system from the previous homeowner and I'm flying a bit blind. He setup the system awhile ago and there are no instructions on how he did what he did. He just has this Raspberry Pi system running Homebridge with the the homebridge-nuvo plugin. Everything was there in the accessory list before we cleared that cache as expected. Clearing the cache removed everything, but now nothing shows up in that list no matter what I do.

**Comment by Willmac16** [comment]
The accessories should repopulate when you restart homebridge, but send the log if an error comes up

**Comment by gschaynes** [comment]
Ya that's what I would have thought as well. I don't even get a "Default" Room anymore. 

This is what comes up on sever reboot:

[3/1/2022, 10:18:27 AM] [Homebridge UI] Rebooting linux server with command: "sudo -n shutdown -r now"
[3/1/2022, 10:18:28 AM] [HB Supervisor] Stopping services...
[3/1/2022, 10:18:28 AM] Got SIGTERM, shutting down Homebridge...
[3/1/2022, 10:18:28 AM] Got SIGTERM, shutting down child bridge process...
[3/1/2022, 10:18:33 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[3/1/2022, 10:18:45 AM] [HB Supervisor] OS: Linux 5.10.17-v7l+ arm
[3/1/2022, 10:18:45 AM] [HB Supervisor] Node.js v14.16.1 /usr/bin/node
[3/1/2022, 10:18:45 AM] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[3/1/2022, 10:18:45 AM] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[3/1/2022, 10:18:52 AM] [Homebridge UI] Homebridge Config UI X v4.42.0 is listening on :: port 8581
[3/1/2022, 10:18:52 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[3/1/2022, 10:18:52 AM] [HB Supervisor] Started Homebridge v1.4.0 with PID: 687
[3/1/2022, 10:18:54 AM] Loaded config.json with 0 accessories and 2 platforms.
[3/1/2022, 10:18:54 AM] Loaded 0 cached accessories from cachedAccessories.
[3/1/2022, 10:18:54 AM] ---
[3/1/2022, 10:18:55 AM] Loaded plugin: homebridge-config-ui-x@4.42.0
[3/1/2022, 10:18:55 AM] Registering platform 'homebridge-config-ui-x.config'
[3/1/2022, 10:18:55 AM] ---
[3/1/2022, 10:18:55 AM] Loaded plugin: homebridge-nuvo@2.2.6
[3/1/2022, 10:18:55 AM] Registering platform 'homebridge-nuvo.nuvo-platform'
[3/1/2022, 10:18:55 AM] ---
[3/1/2022, 10:18:55 AM] Loading 2 platforms...
[3/1/2022, 10:18:55 AM] [Config] Initializing config platform...
[3/1/2022, 10:18:55 AM] [Config] Running in Service Mode
[3/1/2022, 10:18:55 AM] [nuvo-platform] Initializing nuvo-platform platform...
[3/1/2022, 10:18:55 AM] [nuvo-platform] Initializing child bridge 0E:56:A4:8C:A8:B7
Setup Payload:
X-HM://0024KHOWX6338
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │   
    └────────────┘     
                       
[3/1/2022, 10:18:55 AM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 4695) is running on port 51930.
[3/1/2022, 10:18:56 AM] [homebridge-nuvo] Launched child bridge with PID 729
[3/1/2022, 10:18:56 AM] Registering platform 'homebridge-nuvo.nuvo-platform'
[3/1/2022, 10:18:56 AM] [homebridge-nuvo] Loaded homebridge-nuvo v2.2.6 child bridge successfully
[3/1/2022, 10:18:56 AM] Loaded 0 cached accessories from cachedAccessories.0E56A48CA8B7.
[3/1/2022, 10:18:56 AM] Homebridge v1.4.0 (HAP v0.10.0) (homebridge-nuvo) is running on port 40083.
(node:729) UnhandledPromiseRejectionWarning: TypeError: SerialPort is not a constructor
    at new NuvoSerial (/usr/lib/node_modules/homebridge-nuvo/src/serial.ts:26:21)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-nuvo/src/platform.ts:103:37)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/lib/node_modules/homebridge/src/childBridgeFork.ts:173:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Willmac16** [comment]
This looks like an issue in my code. I suspect something changed with the SerialPort dependency after I released the code (since I'm pretty sure things worked before) and my code didn't properly address that or properly restrict which version to use.

**Comment by gschaynes** [comment]
Ahh gotcha kk

**Comment by gschaynes** [comment]
Is there any other log you'd like me to try to grab for you?

**Comment by Willmac16** [comment]
You could try installing an earlier version of homebridge-nuvo, but if I'm correct then that may or may not fix things.

**Comment by gschaynes** [comment]
I'll try that

**Comment by gschaynes** [comment]
Your assumptions are correct. It won't let me install anything before 2.0.0 and I'm getting the same log basically.

**Comment by Willmac16** [comment]
Let me know if the new version works for you
