### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by davidkm123** [Willmac16/homebridge-nuvo#4]
Hi, 

after start I get this error. Can you help me? 

Thx

]
[4/3/2020, 9:12:11 PM] [nuvo-platform] Starting Scan for 1 zones.
[4/3/2020, 9:12:11 PM] [nuvo-platform] Initializing platform accessory 'Pracovna Server 1'...
[4/3/2020, 9:12:11 PM] [nuvo-platform] Initializing platform accessory 'Pracovna aaaaaa'...
[4/3/2020, 9:12:11 PM] [nuvo-platform] Initializing platform accessory 'Pracovna iEastPlayer'...
[4/3/2020, 9:12:11 PM] [nuvo-platform] Initializing platform accessory 'Pracovna aaaaaa'...
[4/3/2020, 9:12:11 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d2545a31-72f4-408a-92df-3b1cee0b4e0e
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:416:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-nuvo/platform.js:62:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[4/3/2020, 9:12:11 PM] Got SIGTERM, shutting down Homebridge...
[4/3/2020, 9:12:16 PM] [HB Supervisor] Homebridge Process Ended. Co

this is my config

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-155"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",
    "platforms": [
        {
            "platform": "FibaroHC2",
            "name": "FibaroHC2",
            "host": "192.168.0.113",
            "username": "homebridge",
            "password": "********",
            "grouping": "none",
            "pollerperiod": "2"
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "nuvo-platform",
            "port": "/dev/tty.usbserial",
            "numZones": 1
        }
    ],
    "accessories": []
}

**Comment by Willmac16** [comment]
Hi, so sorry to get around to this so late. I just made some changes that should help. If they do not help, that looks like the UUID error that homebridge sometimes throws if you restart it and it tries to add back the same accessory, which I believe can be solved by deleting ~/.homebridge/accessories/cachedAccesories or something similar. Let me know how it goes.

**Comment by stuartpreston** [comment]
For anyone who finds this later, I found that in my Grand Concerto configuration, I had two sources named the same "unused". I reconfigured them to be unique "unused 1" and "unused 2" and then after deleting `~/.homebridge/accessories/cachedAccessories` file and restarting the Homebridge service everything worked fine for me. YMMV!

**Comment by Willmac16** [comment]
The new release should fix this behavior, and I made a new tool that will let you do some configuration on the nuvo itself using the same computer that you run homebridge on.

**Comment by stuartpreston** [comment]
Nice! A "nuvo-cli" tool would be excellent.

**Comment by Willmac16** [comment]
The first proper version of nuvo-config is packaged with version 2.2.0. It has support for enabling/disabling, renaming, and tweaking eq settings for zones and sources.
